name:                rearrange-afrp
version:             0.1.0.0
github:              "githubuser/rearrange-afrp"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/rearrange-afrp#readme>

dependencies:
- base >= 4.7 && < 5
- type-level-sets
- first-class-families
- monad-var
- data-default
- haskell-src-exts
- haskell-src-meta
- haskell-src-exts-util
- containers
- megaparsec
- template-haskell
- hedgehog

default-extensions:
- GADTs
- MultiParamTypeClasses
- DataKinds
- PolyKinds
- FlexibleInstances
- BangPatterns
- TypeFamilies
- ExplicitForAll
- StandaloneKindSignatures
- TypeOperators
- ConstraintKinds
- TypeApplications
- FlexibleContexts
- TemplateHaskell
- QuasiQuotes
- PartialTypeSignatures
language: GHC2021

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
# - -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-star-is-type

library:
  source-dirs:
  - src
  - gen

executables:
  rearrange-afrp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rearrange-afrp

tests:
  rearrange-afrp-test:
    main:                Spec.hs
    source-dirs:
    - gen
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rearrange-afrp
